version: '3'

services:
  postgres:
    image: 'postgres:10'
    container_name: 'java-postgres'
    environment:
      - 'POSTGRES_USER=test'
      - 'POSTGRES_PASSWORD=test'
      - 'POSTGRES_DB=employeedb'
    volumes:
      - ./scriptsForDB:/docker-entrypoint-initdb.d
    networks:
      - testnetwork1

  app:
    build: ./
    container_name: 'java-app'
    ports:
      - 8080:8080
    networks:
      - testnetwork1

networks:
  testnetwork1:
